wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: examples._type
      5: 1
      6:
      - 1
    - 1: examples.width
      5: 1
      6:
      - 1
    - 1: examples.height
      5: 1
      6:
      - 1
    - 1: examples.format
      5: 1
      6:
      - 1
    - 1: examples.count
      5: 1
      6:
      - 1
    - 1: examples.captions
      5: 1
      6:
      - 1
    - 1: global_step
      5: 1
      6:
      - 1
    - 1: train/loss_step
      5: 1
      6:
      - 1
    - 1: train/acc_step
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train/val_loss
      5: 1
      6:
      - 1
    - 1: train/val_acc
      5: 1
      6:
      - 1
    - 1: train/loss_epoch
      5: 1
      6:
      - 1
    - 1: train/acc_epoch
      5: 1
      6:
      - 1
    python_version: 3.8.12
    start_time: 1641632464
    t:
      1:
      - 1
      - 9
      2:
      - 1
      - 9
      3:
      - 7
      4: 3.8.12
      5: 0.12.9
      8:
      - 4
      - 5
learning_rate:
  desc: null
  value: 0.01
